#
logging: 
  config: classpath:logback-zkweb.xml
spring: 
  h2: 
    console: 
      enabled: 'true'
      path: /console
      settings: 
        trace: false
        web-allow-others: 'true'
  jta:
    enabled: false
  hateoas: 
    use-hal-as-default-json-media-type: 'false'
  http:
    encoding:
      force: true
  thymeleaf: 
    enabled: false
    cache: false
  datasource:
    platform: h2
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:h2:file:~/.h2/zkweb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;FILE_LOCK=SOCKET
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    initial-pool-size: 10
    min-pool-size: 5
    max-pool-size: 20
    acquire-increment: 3 
    idle-connection-test-period: 60  
    max-idle-time: 60 
    max-statements: 100
    acquire-retry-attempts: 30
    break-after-acquire-failure: false
  resources:
    cache:
      period: 0
#    static-locations:
#      - classpath:/META-INF/resources/
#      - classpath:/resources/
#      - classpath:/static/
#      - classpath:/public/
  profiles:
    active: local
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  session:
    store-type: NONE
  cache:
    type: NONE
  #freemarker
#  freemarker:
#    allow-request-override: false
#    cache: true
#    check-template-location: true
#    charset: UTF-8
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: false
server: 
  port: 8099
  servlet:
    session:
      timeout: 60
    contextPath: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 80
